#!/usr/bin/env python3

import json
import pathlib
import sys
import subprocess
import os
import array
import socket
import struct
import ipaddress

from datetime import datetime, timezone

LOG = pathlib.Path("/tmp/host-bridge.log")

def log_request(data=None):
    timestamp = datetime.now(timezone.utc).isoformat()

    with LOG.open("a", encoding="utf-8") as f:
        f.write("\n" + "=" * 80 + "\n")
        f.write(f"timestamp: {timestamp}\n")
        f.write(f"argv: {json.dumps(sys.argv)}\n")

        if data is not None:
            f.write("request:\n")
            f.write(json.dumps(data, indent=4))
            f.write("\n")

def run_command(command):
    timestamp = datetime.now(timezone.utc).isoformat()

    result = subprocess.run(
        command,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )

    with LOG.open("a", encoding="utf-8") as f:
        f.write("\n" + "=" * 80 + "\n")
        f.write(f"timestamp: {timestamp}\n")
        f.write(f"command: {command!r}\n")
        f.write(f"returncode: {result.returncode}\n")
        f.write("output:\n")
        f.write(result.stdout)

        if not result.stdout.endswith("\n"):
            f.write("\n")

    return result.returncode


def run_nsenter(netns, command):
    return run_command([
        "nsenter",
        f"--net={netns}",
        *command,
    ])

def run_helper(netns, request):
    # Open the namespace file.
    fd = os.open(netns, os.O_RDONLY)

    # Connect to the daemon.
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.settimeout(5.0) # seconds
    sock.connect("/tmp/podman-netd.sock")

    # Send one byte plus the file descriptor.
    fds = array.array("i", [fd])

    sock.sendmsg(
        [json.dumps(request).encode("utf-8")],
        [(socket.SOL_SOCKET,
          socket.SCM_RIGHTS,
          fds.tobytes())]
    )

    reply = sock.recv(65536)
    response = json.loads(reply.decode("utf-8"))

    if response["status"] != "ok":
        raise RuntimeError(response["message"])

    sock.close()
    os.close(fd)


def find_subnet(subnets, ip, no_default_route=False):
    ip = ipaddress.ip_address(ip)
    for subnet in subnets:
        net = ipaddress.ip_network(subnet["subnet"], strict=False)
        if ip in net:
            gw = None if no_default_route else subnet["gateway"]
            return ("/" + str(net.prefixlen), gw)

    return (None, None)


def read_request():
    try:
        return json.load(sys.stdin)
    except json.JSONDecodeError:
        return None


def cmd_info():
    json.dump({
        "version": "0.1",
        "api_version": "1.0.0",
    }, sys.stdout)


def cmd_create():
    data = read_request()
    log_request(data)

    json.dump(data, sys.stdout)


def cmd_setup():
    netns = sys.argv[2] if len(sys.argv) > 2 else None
    data = read_request()
    log_request(data)

    # TODO data["network_options"]["options"] exists only if extra options are
    # passed directly to netavark. See the `man podman-run` documentation for
    # the --network parameter.
    # Validate that data["network_options"]["options"]["bridge"] exists and
    # fail with a meaningful error if it doesn't.
    run_helper(netns, {
        "action": "setup",
        "ifname": data["network_options"]["interface_name"],
        "alias": data["network_options"]["aliases"][0],
        "bridge": data["network_options"]["options"]["bridge"]
    })

    if data["network_options"]["static_mac"]:
        run_nsenter(netns, [
            "ip", "link", "set",
            data["network_options"]["interface_name"],
            "addr", data["network_options"]["static_mac"]
        ])

    run_nsenter(netns, [
        "ip", "link", "set",
        data["network_options"]["interface_name"], "up"
    ])

    # If the network is created with "--opt=no_default_route",
    # ["subnets"][0]["gateway"] is not passed in the create request
    # to the plugin, but for subsequent containers using that network,
    # ["network"]["subnets"][0]["gateway"] is still passed. However,
    # ["network"]["options"]["no_default_route"] is passed too, so
    # clear the gw explicitly in that case.
    nodr = "no_default_route" in data["network"].get("options", {})
    for ip in data["network_options"]["static_ips"]:
        mask, gw = find_subnet(data["network"]["subnets"], ip, nodr)
        if mask:
            run_nsenter(netns, [
                "ip", "addr", "add", ip + mask,
                "dev", data["network_options"]["interface_name"]
            ])
        if gw:
            run_nsenter(netns, [
                "ip", "route", "add", "default",
                "via", gw,
                "dev", data["network_options"]["interface_name"]
            ])

    json.dump({
        "dns_search_domains": [],
        "dns_server_ips": [],
        "interfaces": {}
    }, sys.stdout)


def cmd_teardown():
    netns = sys.argv[2] if len(sys.argv) > 2 else None
    data = read_request()
    log_request(data)


def main():
    if len(sys.argv) < 2:
        cmd_info()
        return

    cmd = sys.argv[1]

    if cmd == "info":
        cmd_info()
    elif cmd == "create":
        cmd_create()
    elif cmd == "setup":
        cmd_setup()
    elif cmd == "teardown":
        cmd_teardown()
    else:
        log_request({
            "error": f"unknown command {cmd}"
        })
        print(json.dumps({
            "error": f"Unknown command {cmd}"
        }))
        sys.exit(1)


if __name__ == "__main__":
    main()
