#!/usr/bin/env python3

import configparser
import array
import os
import stat
import socket
import struct
import json
import subprocess

def fdpath(fd):
    return f"/proc/self/fd/{fd}"

def handle_request(cfg, request, fd):
    if request["bridge"] not in cfg["allowed-bridge"]:
        return (f"bridge {request["bridge"]} not allowed", None)

    rc = subprocess.run([
        "ip", "link", "add",
        "ve" + request["alias"],
        "type", "veth",
        "peer", request["ifname"],
        "netns", fdpath(fd),
    ], pass_fds=(fd,), text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if rc.returncode != 0:
        return (f"veth error {rc.returncode}", rc.stdout)

    rc = subprocess.run([
        "ip", "link", "set",
        "ve" + request["alias"], "up",
    ], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if rc.returncode != 0:
        return (f"set link up error {rc.returncode}", rc.stdout)

    rc = subprocess.run([
        "ip", "link", "set",
        "ve" + request["alias"],
        "master", request["bridge"],
    ], text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if rc.returncode != 0:
        return (f"set master error {rc.returncode}", rc.stdout)

def handle_connection(cfg, conn):
    #
    # Obtain peer credentials.
    #
    SO_PEERCRED = 17

    creds = conn.getsockopt(
        socket.SOL_SOCKET,
        SO_PEERCRED,
        struct.calcsize("3i"))

    pid, uid, gid = struct.unpack("3i", creds)

    print(f"Peer pid={pid} uid={uid} gid={gid}")

    #
    # Receive the namespace fd.
    #
    fds = array.array("i")

    msg, ancdata, flags, addr = conn.recvmsg(
        4096,
        socket.CMSG_LEN(array.array("i", [0]).itemsize)
    )

    for level, typ, data in ancdata:
        if level == socket.SOL_SOCKET and typ == socket.SCM_RIGHTS:
            fds.frombytes(
                data[:len(data) - (len(data) % fds.itemsize)]
            )

    if len(fds) != 1:
        raise RuntimeError("Did not receive fd")

    fd = fds[0]

    print("Received fd =", fd)

    st = os.fstat(fd)

    print("st_dev =", st.st_dev)
    print("st_ino =", st.st_ino)
    print("st_mode =", oct(st.st_mode))

    print("readlink: " + os.readlink(fdpath(fd)))

    request = json.loads(msg.decode("utf-8"))

    print("Request:")
    print(json.dumps(request, indent=4))

    response = {"status": "ok"}
    errval = handle_request(cfg, request, fd)
    if errval:
        response = {
            "status": "error",
            "message": errval[0],
        }
        if errval[1]:
            print(errval[1])
    conn.sendmsg([json.dumps(response).encode("utf-8")])

    os.close(fd)
    conn.close()

def main():
    #
    # Read configuration
    #
    cfg = configparser.ConfigParser()
    cfg.read("/etc/podman-netd.conf")
    cfg = {
        "allowed-bridge": [x.strip() for x in cfg['DEFAULT']['allowed-bridge'].split(',')],
    }

    #
    # Get connection socket from systemd
    #
    print(os.environ.get("LISTEN_PID", "0"))
    print(os.getpid())
    if int(os.environ.get("LISTEN_PID", "0")) != os.getpid():
        raise RuntimeError("not socket activated")

    n = int(os.environ.get("LISTEN_FDS", "0"))

    if n != 1:
        raise RuntimeError("expected one socket")

    server = socket.fromfd(
        3,
        socket.AF_UNIX,
        socket.SOCK_STREAM,
    )

    while True:
        conn, addr = server.accept()
        handle_connection(cfg, conn)

    server.close()

if __name__ == "__main__":
    main()
