#!/usr/bin/env python3

import os
import re
import subprocess
import sys
from pathlib import Path


def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def validate_alias(alias):
    if not re.fullmatch(r"[0-9a-fA-F]{12}", alias):
        die("alias must be exactly 12 hexadecimal digits")


def validate_netns(netns, uid):
    base = Path(f"/run/user/{uid}")

    try:
        resolved = Path(netns).resolve(strict=True)
    except FileNotFoundError:
        die("netns path does not exist")

    try:
        resolved.relative_to(base)
    except ValueError:
        die(f"netns {resolved} is not under {base}")

    return str(resolved)


def run_ip(*args):
    cmd = ["ip", *args]
    print("+", " ".join(cmd), file=sys.stderr)

    subprocess.run(
        cmd,
        check=True,
    )


def setup(interface, alias, netns):
    host_if = "ve" + alias

    # Create veth pair:
    #
    # host:
    #     veXXXXXXXXXXXX
    #
    # netns:
    #     <interface>
    #
    run_ip(
        "link",
        "add",
        host_if,
        "type",
        "veth",
        "peer",
        "name",
        interface,
        "netns",
        netns,
    )

    print(f"created {host_if} <-> {interface}")


def teardown(interface, alias, netns):
    # TODO
    pass


def main():
    uid = int(os.environ.get('SUDO_UID', os.getuid()))
    if uid == 0:
        die("calling user cannot be root")

    if len(sys.argv) != 6:
        die(
            "usage: helper <setup|teardown> <interface> <alias> <netns> <bridge>"
        )

    action = sys.argv[1]
    interface = sys.argv[2]
    alias = sys.argv[3]
    netns = sys.argv[4]
    bridge = sys.argv[5]

    if action not in ("setup", "teardown"):
        die("action must be setup or teardown")

    validate_alias(alias)
    netns = validate_netns(netns, uid)

    if action == "setup":
        setup(interface, alias, netns)

    elif action == "teardown":
        teardown(interface, alias, netns)


if __name__ == "__main__":
    main()
